
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ressential.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Account
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Account()
    {

        this.PaymentVouchers = new HashSet<PaymentVoucher>();

        this.ReceiptVouchers = new HashSet<ReceiptVoucher>();

    }


    public int AccountId { get; set; }

    public string AccountType { get; set; }

    public string AccountTitle { get; set; }

    public string BankName { get; set; }

    public string AccountNumber { get; set; }

    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedAt { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PaymentVoucher> PaymentVouchers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReceiptVoucher> ReceiptVouchers { get; set; }

}

}
