//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchItem
    {
        public int BranchItemId { get; set; }
        public int ItemId { get; set; }
        public int BranchId { get; set; }
        public decimal MinimumStockLevel { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostPerUnit { get; set; }
        public decimal OpeningStockQuantity { get; set; }
        public decimal OpeningStockValue { get; set; }
        public System.DateTime OpeningStockDate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string StockLevelState { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
        public virtual Item Item { get; set; }
        public virtual User User1 { get; set; }
    }
}
