//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchArea
    {
        public int BranchAreaId { get; set; }
        public int BranchId { get; set; }
        public int AreaId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
    }
}
