//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.BranchItemDetails = new HashSet<BranchItemDetail>();
            this.ConsumeItemDetails = new HashSet<ConsumeItemDetail>();
            this.ProductItemDetails = new HashSet<ProductItemDetail>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
            this.PurchasesReturnDetails = new HashSet<PurchasesReturnDetail>();
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
            this.ReturnStockDetails = new HashSet<ReturnStockDetail>();
            this.WarehouseIssueDetails = new HashSet<WarehouseIssueDetail>();
            this.WastageItemDetails = new HashSet<WastageItemDetail>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Sku { get; set; }
        public int ItemCategoryId { get; set; }
        public int UnitOfMeasureId { get; set; }
        public decimal MinimumStockLevel { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchItemDetail> BranchItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumeItemDetail> ConsumeItemDetails { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductItemDetail> ProductItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasesReturnDetail> PurchasesReturnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnStockDetail> ReturnStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseIssueDetail> WarehouseIssueDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WastageItemDetail> WastageItemDetails { get; set; }
        public virtual WarehouseItemStock WarehouseItemStock { get; set; }
    }
}
