//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RessentialEntities : DbContext
    {
        public DB_RessentialEntities()
            : base("name=DB_RessentialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<BranchArea> BranchAreas { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchItem> BranchItems { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ConsumeItemDetail> ConsumeItemDetails { get; set; }
        public virtual DbSet<ConsumeItem> ConsumeItems { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<OnlineOrderDetail> OnlineOrderDetails { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderReturnDetail> OrderReturnDetails { get; set; }
        public virtual DbSet<OrderReturn> OrderReturns { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PaymentApply> PaymentApplies { get; set; }
        public virtual DbSet<PaymentVoucherAttachment> PaymentVoucherAttachments { get; set; }
        public virtual DbSet<PaymentVoucher> PaymentVouchers { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PermissionsCategory> PermissionsCategories { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductItemDetail> ProductItemDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseReturn> PurchaseReturns { get; set; }
        public virtual DbSet<PurchaseReturnDetail> PurchaseReturnDetails { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<ReceiptApply> ReceiptApplies { get; set; }
        public virtual DbSet<ReceiptVoucherAttachment> ReceiptVoucherAttachments { get; set; }
        public virtual DbSet<ReceiptVoucher> ReceiptVouchers { get; set; }
        public virtual DbSet<RequisitionDetail> RequisitionDetails { get; set; }
        public virtual DbSet<Requisition> Requisitions { get; set; }
        public virtual DbSet<ReturnStock> ReturnStocks { get; set; }
        public virtual DbSet<ReturnStockDetail> ReturnStockDetails { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<WarehouseIssueDetail> WarehouseIssueDetails { get; set; }
        public virtual DbSet<WarehouseIssue> WarehouseIssues { get; set; }
        public virtual DbSet<WarehouseItemStock> WarehouseItemStocks { get; set; }
        public virtual DbSet<WastageItemDetail> WastageItemDetails { get; set; }
        public virtual DbSet<WastageItem> WastageItems { get; set; }
        public virtual DbSet<UserBranchPermission> UserBranchPermissions { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
