//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Message { get; set; }
        public string Type { get; set; }
        public bool IsRead { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
    }
}
