
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ressential.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OnlineOrderDetail
{

    public int OnlineOrderDetailId { get; set; }

    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string ContactNo { get; set; }

    public int DeliveryCharges { get; set; }



    public virtual Order Order { get; set; }

}

}
