//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderReturnDetail
    {
        public int OrderReturnDetailId { get; set; }
        public int OrderReturnId { get; set; }
        public int ProductId { get; set; }
        public decimal ProductQuantity { get; set; }
    
        public virtual OrderReturn OrderReturn { get; set; }
        public virtual Product Product { get; set; }
    }
}
