
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ressential.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.OnlineOrderDetails = new HashSet<OnlineOrderDetail>();

        this.OrderDetails = new HashSet<OrderDetail>();

        this.OrderReturns = new HashSet<OrderReturn>();

    }


    public int OrderId { get; set; }

    public System.DateTime OrderDate { get; set; }

    public string OrderNo { get; set; }

    public string OrderType { get; set; }

    public string TableNo { get; set; }

    public int BranchId { get; set; }

    public Nullable<int> CustomerId { get; set; }

    public string PaymentMethod { get; set; }

    public decimal OrderTotal { get; set; }

    public string Status { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public decimal OrderTotalCost { get; set; }



    public virtual Branch Branch { get; set; }

    public virtual Customer Customer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OnlineOrderDetail> OnlineOrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderReturn> OrderReturns { get; set; }

    public virtual User User { get; set; }

}

}
