
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ressential.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentApply
{

    public int PaymentApplyId { get; set; }

    public int PaymentVoucherId { get; set; }

    public int PurchaseId { get; set; }

    public decimal AppliedAmount { get; set; }



    public virtual PaymentVoucher PaymentVoucher { get; set; }

    public virtual Purchase Purchase { get; set; }

}

}
