
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ressential.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentVoucher
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PaymentVoucher()
    {

        this.PaymentApplies = new HashSet<PaymentApply>();

        this.PaymentVoucherAttachments = new HashSet<PaymentVoucherAttachment>();

    }


    public int PaymentVoucherId { get; set; }

    public string PaymentVoucherNo { get; set; }

    public System.DateTime PaymentVoucherDate { get; set; }

    public int VendorId { get; set; }

    public int AccountId { get; set; }

    public string InstrumentNo { get; set; }

    public Nullable<System.DateTime> InstrumentDate { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedAt { get; set; }



    public virtual Account Account { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PaymentApply> PaymentApplies { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PaymentVoucherAttachment> PaymentVoucherAttachments { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual Vendor Vendor { get; set; }

}

}
