//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItemDetail
    {
        public int ProductItemDetailId { get; set; }
        public int ProductId { get; set; }
        public int ItemId { get; set; }
        public decimal ItemQuantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Product Product { get; set; }
    }
}
