//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptApply
    {
        public int ReceiptApplyId { get; set; }
        public int ReceiptVoucherId { get; set; }
        public int PurchaseReturnId { get; set; }
        public decimal AppliedAmount { get; set; }
    
        public virtual PurchaseReturn PurchaseReturn { get; set; }
        public virtual ReceiptVoucher ReceiptVoucher { get; set; }
    }
}
