//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptVoucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiptVoucher()
        {
            this.ReceiptApplies = new HashSet<ReceiptApply>();
            this.ReceiptVoucherAttachments = new HashSet<ReceiptVoucherAttachment>();
        }
    
        public int ReceiptVoucherId { get; set; }
        public string ReceiptVoucherNo { get; set; }
        public System.DateTime ReceiptVoucherDate { get; set; }
        public int VendorId { get; set; }
        public int AccountId { get; set; }
        public string InstrumentNo { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptApply> ReceiptApplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptVoucherAttachment> ReceiptVoucherAttachments { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
