
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ressential.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Requisition
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Requisition()
    {

        this.RequisitionDetails = new HashSet<RequisitionDetail>();

        this.WarehouseIssues = new HashSet<WarehouseIssue>();

    }


    public int RequisitionId { get; set; }

    public string RequisitionNo { get; set; }

    public System.DateTime RequisitionDate { get; set; }

    public int BranchId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedAt { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedAt { get; set; }



    public virtual Branch Branch { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WarehouseIssue> WarehouseIssues { get; set; }

}

}
