//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressential.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseIssueDetail
    {
        public int IssueDetailId { get; set; }
        public int IssueId { get; set; }
        public Nullable<int> RequisitionId { get; set; }
        public int ItemId { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostApplied { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
        public virtual WarehouseIssue WarehouseIssue { get; set; }
    }
}
